[project]
name = "datasci-210-2025-summer-formula1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastf1>=3.5.3",
    "pandera[pandas]>=0.24.0",
    "tqdm>=4.67.1",
]
