apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - name: timescaledb
        image: timescale/timescaledb:latest-pg15
        env:
        - name: POSTGRES_DB
          value: racing_telemetry
        - name: POSTGRES_USER
          value: racing_user
        - name: POSTGRES_PASSWORD
          value: racing_password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb-service
spec:
  selector:
    app: timescaledb
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
