apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: f1
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: f1
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels: { app: db }
  template:
    metadata:
      labels: { app: db }
    spec:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: db
          image: 590184119443.dkr.ecr.us-east-1.amazonaws.com/f1/database:latest
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata   # <-- use a subdir
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef: { name: model-service-config, key: POSTGRES_DB }
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef: { name: model-service-config, key: POSTGRES_USER }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: db-secrets, key: POSTGRES_PASSWORD }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data        # keep mount at parent
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests: { storage: 20Gi }
        
