apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: f1
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: f1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: app
          image: 590184119443.dkr.ecr.us-east-1.amazonaws.com/f1/webapp:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef: { name: webapp-config }
          env:
            - name: API_BASE_URL
              value: "http://model-service:8000"        # from compose intent
            - name: MONTE_CARLO_BASE_URL
              value: "http://monte-carlo-sim:8001"      # from compose intent
          readinessProbe:
            httpGet: { path: "/", port: 5000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 5000 }
            initialDelaySeconds: 20
            periodSeconds: 10
