apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
  namespace: w255
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-api-deployment
  template:
    metadata:
      labels:
        app: python-api-deployment
    spec:
      initContainers:
        - name: init-verify-redis-service-dns
          image: busybox
          command:
            - sh
            - -c
            - "until nslookup redis-service.w255.svc.cluster.local; do echo waiting for redis service; sleep 2; done"
        - name: init-verify-redis-ready
          image: busybox
          command:
            - sh
            - -c
            - "until nc -zv redis-service.w255.svc.cluster.local 6379; do echo waiting for redis to be ready; sleep 2; done"
      containers:
        - name: python-api
          image: lab3
          imagePullPolicy: Never  # to ensure the local image is used
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /lab/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /lab/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /lab/health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
